### ISSUE TITLE
LaTeX symbol expanding line height

### ISSUE THREAD

**Issue by wetneb** [cpitclaudel/company-coq#117] opened 2016-05-12 04:13 UTC
Thank you so much for company-coq, it is very enjoyable to use coq with it!
Here is something that is slightly annoying though:
<pre>
Require Import QArith.
Infix "\preceq" := Qle (at level 70).`
</pre>
renders as
![preceq bug](http://pintoch.ulminfo.fr/2d9d9c2b0e/preceq.png)

The line width of any line that includes the "\preceq" symbol is expanded a lot (as you can see with the highlighted brackets). It would be great if line height could be preserved.

**Comment by cpitclaudel** [comment] 2016-05-12 06:01
Hi Antonin,

Thanks for your nice comments :) I think installing a good unicode math font (see https://github.com/cpitclaudel/company-coq#installing-a-math-font) should do the trick :)

There's more details about this issue in #15 (see also #31). If you're interested in the gory details, you can read the whole Emacs bug thread at https://lists.gnu.org/archive/html/bug-gnu-emacs/2015-05/msg00696.html (the issue is fixed in Emacs 25).

Let me know if that helps!

**Comment by wetneb** [comment] 2016-05-12 06:14
It does work \o/
Thank you very much, sorry for not having RTFM first!

**Closed** 2016-05-12 06:15 UTC

**Comment by cpitclaudel** [comment] 2016-05-12 08:07
No problem :) Glad to know that it's working now.
