### ISSUE TITLE
The script P folding for Prop takes up several lines

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#31] opened 2015-12-22 00:11 UTC
I  know that emacs way of dealing with fonts involves black magic - so this might just be a manifestation of my local environment.  The script P used as the folding of Prop takes up what appears to be several lines, even though the character itself doesn't.  I temporarily worked around this by changing the mapping in company-coq-prettify-symbols-alist to use a different fancy P.

The same is apparently true for the script N for nat, and a few other symbols.  Here's (hopefully, if attaching a file works) a screen shot of the etc/symbols file - note that those apparently blank lines aren't lines at all:

![screenshot-symbols](https://cloud.githubusercontent.com/assets/7363878/11944746/50800b92-a816-11e5-90b0-69d3a9235f35.png)

**Comment by cpitclaudel** [comment] 2015-12-22 03:32
Hi Jonathan,

Fortunately, this magic is relatively well understood now :) I think you have a duplicate of https://github.com/cpitclaudel/company-coq/issues/15 , which itself is handled [way way way down the readme](https://github.com/cpitclaudel/company-coq#empty-squares-in-place-of-math-operators-or-incorrect-line-spacing).

It boils down to a combination of the LaTeX fonts (which is what is being used) not having the right metrics (they specify maximum ascent and descent where they should specify base ascent and descent), and Emacs not handling this case properly. 

The Emacs part is fixed in Emacs 25, based on a bug report that I filed. The bad metrics part is fixed in the copy of the fonts that I distribute at https://github.com/cpitclaudel/monospacifier. And of course you can sidestep the issue entirely by using a different fallback font (I recommend Symbola at http://users.teilar.gr/~g1951d/Symbola.zip).

Let me know if that does the trick!

**Comment by jonleivent** [comment] 2015-12-22 15:36
I am trying to use the Symbola fonts you provide at monospacifier for Inconsolata and DejaVu Sans Mono, but for some reason, the font manager on my machine (running Debian Jessie) is not picking up those fonts properly.  I was able to load Symbola from http://users.teilar.gr/%7Eg1951d/Symbola.zip without a problem.  Could there be something wrong with the Symbola_monospaced_for_... fonts you are providing?  The strange thing is that the font manager is not giving me any error when loading those fonts, they just are not showing up after loading.  They are placed in the font folder under: /home/jil/.fonts/Library/S, but I just can't see them as options in the font manager or when doing Emacs Options->Set Default Font.

By the way - I apologize for not noticing #15 in the readme as the possible solution.

It is working for me to use pure Symbola as the fallback via:
(set-fontset-font t 'unicode (font-spec :name "Symbola") nil 'append)
for all symbol foldings except the squiggly left arrow for <++

**Comment by cpitclaudel** [comment] 2015-12-22 16:16
Glad to hear this is fixed. `<++` was a bit of an esoteric character anyway; it won't be in the next release.

As for the monospacified version of Symbola, did you run `fc-cache` after installing it?

**Comment by cpitclaudel** [comment] 2015-12-22 16:17
I'll try on Debian Jessie; is this emacs 24.5?

**Comment by jonleivent** [comment] 2015-12-22 16:31
I tried calling fc-cache, and also running the GUI font-manager application (installed from the Debian repo).  Neither worked - but using the GUI font-manager did work for installing the pure Symbola font - so I know I did the right thing:

![screenshot-font manager](https://cloud.githubusercontent.com/assets/7363878/11960144/2a4c39bc-a89f-11e5-807a-f39366182052.png)

Is it possible that I have to have had the pure Symbola font installed prior to the monospace variants?  Maybe I need to somehow undo those broken additions and start over?

**Comment by jonleivent** [comment] 2015-12-22 16:33
OH - forgot: emacs 24.4.1.  Which is what is current in Jessie's stable repo.

**Comment by jonleivent** [comment] 2015-12-23 00:46
I got it to work, finally!  I'm not even sure which of the following I did made it work: 

- removing the monospacified fonts and reinstalling them after successfully installing pure Symbola

- making sure I reinstalled them from the monospacified/font directory of my git clone instead of from downloading via the readme links

I think it may be the second - meaning that the links from the readme are to old non-working versions?

![screenshot-font manager-1](https://cloud.githubusercontent.com/assets/7363878/11969206/816ec152-a8e4-11e5-9595-f79d813ede0b.png)

**Closed** 2015-12-23 00:50 UTC
Labels: question
