### ISSUE TITLE
Autocompletion gets overexcited when switching to normal mode in spacemacs

### ISSUE THREAD

**Issue by lehmacdj** [cpitclaudel/company-coq#174] opened 2017-09-04 05:18 UTC
I am using spacemacs with vim keybindings. When I change to normal mode from insert mode it seems that autocompletion is inserting strange text.

![coq](https://user-images.githubusercontent.com/13156983/30012509-479b65e8-910e-11e7-868b-b1d2fe3d5db8.gif)

This happens regardless of whether or not I am in a proof context or not. It even happens when I enter insert mode right after a character like `a` or `s` and then immediately leave insert mode (like so):

![coq2](https://user-images.githubusercontent.com/13156983/30012566-df0e23de-910e-11e7-8599-8139546e32e7.gif)

What might cause completion to trigger when leaving insert mode and how can I prevent it without disabling completion completely?

Thanks for making an amazing package and helping me solve this issue

**Comment by DavidGregory084** [comment] 2017-09-08 23:01
@lehmacdj according to https://github.com/syl20bnr/spacemacs/issues/8853 it looks like this can be fixed by setting `https://github.com/syl20bnr/spacemacs/issues/8853` in `dotspacemacs/user-init`

**Comment by lehmacdj** [comment] 2017-09-08 23:02
thanks, I didn’t think to check the spacemacs issues.

Devin Lehmacher

**Closed** 2017-09-08 23:08 UTC

**Comment by cpitclaudel** [comment] 2017-09-10 21:15
Sorry for the delayed answers; indeed, this was a dupe of https://github.com/ProofGeneral/PG/issues/174 :)
