### ISSUE TITLE
Error running timer `company-coq-maybe-reload-each'

### ISSUE THREAD

**Issue by jonleivent** [cpitclaudel/company-coq#94] opened 2016-02-28 23:57 UTC
I decided to enable Coq->Settings->Time Commands, and this apparently causes some issues with Company-Coq.  The full error message in the minibuffer is:

Error running timer `company-coq-maybe-reload-each': (error "Toplevel parsing failure [(\<infomsg\>Finished transaction in 0.002 secs (0.004u (, 0.s)) (successful) \</infomsg\>)]")

**Comment by cpitclaudel** [comment] 2016-02-29 00:05
Oh. Indeed. This is the tactics grammar parser complaining.
I'm not sure that even silent command sent by the prover itself should have timing information, so maybe this is more of a PG bug. Let me see.

**Comment by cpitclaudel** [comment] 2016-02-29 00:31
I've pushed https://github.com/ProofGeneral/PG/commit/11b03d47628bf833e98e0b3d8ae9c5c9a358235d to the PG repo; this should fix this issue.

**Comment by jonleivent** [comment] 2016-02-29 00:38
I just pulled that and rebuilt PG, but it didn't help.  Still getting the same error in the minibuffer.

**Comment by cpitclaudel** [comment] 2016-02-29 00:45
Uh oh.

**Comment by cpitclaudel** [comment] 2016-02-29 00:45
Ok. Let me test this a bit further then.

**Comment by cpitclaudel** [comment] 2016-02-29 05:08
Indeed, `delayed-output-flags

**Comment by cpitclaudel** [comment] 2016-02-29 05:09
Indeed, `delayed-output-flags` aren't available in `shell-insert-hook`. I adjusted the condition. Works for me now.
Sorry about the back and forth!

**Comment by jonleivent** [comment] 2016-02-29 15:06
Now something very bad is happening with respect to Time Commands vs. bullets.  A simple example is a file with just this:

Require Import Omega.

Lemma foo : forall n:nat, n >= 0.
Proof.
  induction n.
  - omega.
  - omega.
Qed.

If I set Time Commands, and then tell PG to process the whole buffer, things hang just before the first bullet.  The coqtop process is not computing at that point (system monitor shows it taking 0% cpu), so something is hung in PG I suppose.

**Comment by jonleivent** [comment] 2016-02-29 15:08
That infernal git markup again!  I really have to remember to do Preview before sending these.  Here's a second try:

Require Import Omega.

Lemma foo : forall n:nat, n >= 0.
Proof.
induction n.
    \- omega.
    \- omega.
Qed.

**Comment by cpitclaudel** [comment] 2016-02-29 16:31
Looks like a PG (or Coq? bug); sending `Time -` to coqtop in `-emacs` mode makes it hang without returning a prompt, apparently. Can you open a PG bug for this? I seem to be able to reproduce it without company-coq, independently of my most recent patches.

**Comment by cpitclaudel** [comment] 2016-02-29 16:36
I've just pushed a fix on the company-coq side, to not depend on the recent PG fix.

**Closed** 2016-02-29 16:36 UTC

**Comment by jonleivent** [comment] 2016-02-29 16:44
Yup - I was able to reproduce it without company-coq as well.  I will open a PG issue...

**Comment by jonleivent** [comment] 2016-02-29 16:49
[https://github.com/ProofGeneral/PG/issues/62](url)
