### ISSUE TITLE
Inconsistent state after error

### ISSUE THREAD

**Issue by vzaliva** [cpitclaudel/company-coq#66] opened 2016-01-24 17:11 UTC
When one of the modules which is I am importing contains syntax error, after error message "Recompling binary failed with X status" company-coq (or proof general) ends up in inconsistent state.
Attempting to step through any proofs leads to error message:

    "Window is dedicated to coq-compile response"

Even though I am focused in right buffer. The only solution is to restart Emacs.

Environment: 
  * Aquamacs 3.2
  * PG 4.3pre150313 (latest from git)
  *  Company-coq latest from MELPA

**Comment by cpitclaudel** [comment] 2016-01-25 13:59
Hi there,
Indeed, that's probably a PG issue.  Are you using automatic compilation or `Require`d modules? I think I ran into this a while ago.

**Comment by vzaliva** [comment] 2016-01-25 19:16
yes, I am using automatic compilation.
I should did not have this problem until I have upgraded to Git snapshot of PG.

**Comment by cpitclaudel** [comment] 2016-01-26 06:18
Got it. This is very likely to be a PG issue, so I opened a bug there. I'll close this one, and will reopen if it turns out that a bad interaction is the cause of this issue.

**Closed by cpitclaudel** 2016-01-26 06:18 UTC
