### ISSUE TITLE
`libxml2 library not found` error when getting help doc with C-h or C-w

### ISSUE THREAD

**Issue by eulerreich** [cpitclaudel/company-coq#20] opened 2015-08-12 05:47 UTC
This is on windows 8.1, with emacs 24.5. I have the libxml2 binary libxml2.dll on the PATH, and I can verify that emacs is getting the PATH via `M-x getenv`. So I'm not sure why it can't find the library.

**Comment by cpitclaudel** [comment] 2015-08-12 06:35
Thanks for the report. `libxml2` is a compile-time dependency: Emacs does not load it dynamically.

The `system-configuration-features` variable contains a list of features that were enabled at build time. does `LIBXML2` appear in that list? (You can print it with <kbd>M-: RET system-configuration-features RET</kbd>). Here's mine for reference:

```
XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM  DBUS GCONF GSETTINGS NOTIFY ACL 
LIBSELINUX GNUTLS  LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
```

Also: where did you download your Emacs from?

**Comment by eulerreich** [comment] 2015-08-12 12:57
I actually can't evaluate `system-configuration-features`. I get the following error
```
Debugger entered--Lisp error: (void-variable system-configuration-features)
  eval(system-configuration-features nil)
  eval-expression(system-configuration-features nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

I downloaded `emacs-24.5-bin-i686-mingw32` from the [emacs ftp](https://ftp.gnu.org/gnu/emacs/windows/)

**Comment by cpitclaudel** [comment] 2015-08-13 05:09
Ah, sorry about that; that variable is new in 25.0.5. You could check if `system-configuration-options` mentions `--without-libxml2`, though I expect it won't given the source. I'll check this on a Windows box soon.

**Comment by eulerreich** [comment] 2015-08-13 07:37
No it does not mention it. I found some threads on the internet like this
<https://www.reddit.com/r/emacs/comments/2o8gxb/help_with_libxml2_on_windows/>
that suggests putting the .dll in the emacs/bin folder, but I tried that
and it didn't work either.

**Comment by cpitclaudel** [comment] 2015-08-14 08:34
Indeed, when I download the emacs that you pointed to and try `eww` I get the same "missing libxml2" error. However, downloading [libxml2](http://sourceforge.net/projects/ezwinports/files/libxml2-2.7.8-w32-bin.zip/download) (found by reading https://lists.gnu.org/archive/html/emacs-devel/2012-02/msg00077.html) and extracting it to the folder when I originally extracted emacs fixes the issue. Can you try that?

**Comment by eulerreich** [comment] 2015-08-14 13:22
Like I said in the last post, I've already tried that and it doesn't work for me. Here's what happens if I type `appl` in company-coq mode and then press C-h: The minibuffer tells me `uncompressing 6w.html.gz...done` but doesn't give me the `libxml2 library not found` error. But on the second time I press C-h, it gives me both of them. I'm not sure if this helps.

**Comment by cpitclaudel** [comment] 2015-08-14 15:36
> Like I said in the last post, I've already tried that and it doesn't work for me.

Sorry about that. From your last post I gathered that you tried copying a particular dll in your emacs/bin folder. This is not what I suggested; instead, I suggested downloading the full libxml2 package and extracting it to your emacs folder. This worked for me on Windows 8, after doanlowding the release that you pointed to.

Is the problem actually specific to company-coq? It could be that copying the contents of the libxml2 package fixed one part of the problem, but company-coq still has an issue. It's easy to check that; run `M-x eww RET github.com RET`. Does Emacs complain about libxml2 then? If so, then this issue is not connected to company-coq. In that case, I would suggest taking the following steps:

1. Download a clean emacs from https://ftp.gnu.org/gnu/emacs/windows/emacs-24.5-bin-i686-mingw32.zip
2. Download a clean libxml2 from https://sourceforge.net/projects/ezwinports/files/libxml2-2.7.8-w32-bin.zip/download
3. Create an emacs directory on your desktop and extract both archives to that folder
4. Launch the `runemacs` program found in the newly created emacs/bin directory
5. Run `M-x eww RET github.com RET`

On the other hand, if the problem is indeed specific to company-coq, we can try to diagnose it further.

**Comment by eulerreich** [comment] 2015-08-14 23:20
Yea it's a eww problem. I can't get it to work by just putting the libxml2
folder inside the emacs folder.

**Comment by eulerreich** [comment] 2015-08-14 23:42
I tried the clean emacs solution but it didn't work (but I'm not sure it
was clean since they at least shared .emacs.d and .emacs, which I renamed,
and there are probably some other shared files that I'm not aware of?)

**Comment by AntJanus** [comment] 2015-12-19 05:35
@eulerreich did you ever resolve the issue? or at least found a binary that includes all of the necessary libraries?

**Comment by eulerreich** [comment] 2015-12-19 15:19
No I don't think so.

**Comment by cpitclaudel** [comment] 2015-12-19 16:35
@AntJanus Which version of Windows are you using? And can you open eww?

**Comment by AntJanus** [comment] 2015-12-21 15:24
Ahh, you know, I've just been able to resolve it. And I wish I could remember how I did it. It involved getting a different version of libxml2 than the one I was originally dropping into the folder :/

**Comment by cpitclaudel** [comment] 2015-12-22 15:43
Ok, I'll close this then. @AntJanus, if you manage to reproduce the solution (:smiley:), please do add info here!

**Closed by cpitclaudel** 2015-12-22 15:43 UTC

**Comment by PFDstudio** [comment] 2016-09-22 17:25
I'd love to hear the solution, as I'm having the same problem now with Windows 10/Emacs 25.1.1.

Thanks.

**Comment by PFDstudio** [comment] 2016-09-26 15:29
Yes, I did. Everything from the libxml2 zip got placed in the corresponding folders of the emacs directory, and I restarted emacs, but I still get the 'libxml2 library not found' error.

Thanks!

**Comment by cpitclaudel** [comment] 2016-09-26 15:48
Ok. Try checking whether you're using the right library for your version of Emacs.  It could be that you're using a 64 bits emacs with a 32 bits lib, or the other way around.

**Comment by PFDstudio** [comment] 2016-09-27 15:44
Interesting possibility. emacs-version says it's 64 bit, but I don't see anything in the library (unless it's the win32 name ... but I haven't found any win64 versions of libxml).

**Comment by PFDstudio** [comment] 2016-09-27 16:20
D'oh! I did discover the 64bit subdirectory, but even after copying that 7z file and unpacking it to my emacs directory, and launching a new instance of emacs, I'm *still* getting the library not found message.

Thanks!

**Comment by cpitclaudel** [comment] 2016-09-27 17:34
Ok. Let's do this from scratch :)

Download emacs 25 from ftp://ftp.gnu.org/gnu/emacs/windows/emacs-25.1-x86_64-w64-mingw32.zip
Download the dependencies from http://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-25-x86_64-deps.zip

Unpack both in the same place and try again :)

**Comment by PFDstudio** [comment] 2016-10-26 14:27
Aha! Sorry, I've been away from this for a while, but finally getting back to it. It seems you found the correct emacs and dependencies. Thank you! Gnus is working again at last.

Thank you!

-pd

**Comment by junjiemars** [comment] 2016-12-27 03:14
On Windows 10, Emacs-25.1-2 x86_64, libxml2 from http://xmlsoft.org/sources/win32/64bit/libxml2-2.9.3-win32-x86_64.7z is works for me.

**Comment by Thanh9356** [comment] 2018-03-17 13:34
cpitclaudel I found a better way. It's in libexec\emacs\i686-pc-mingw32 you can see a zip file and extract them(may be it will be other in another PCs)

**Comment by stralx** [comment] 2018-04-17 21:33
junliemars thank you! I've lost a couple of hours in this one!
For the record I'm using MSYS2 64bit in windows 8.1 and emacs25.3_1 so I think of it like a virtual machine. I haven't got any "clean extraction folder" for emacs because I installed it with pacman. I figured out that I should put the libxml2 extracted folders in my msys2 /usr folder. Then again nothing was working until I got juliemars' link! So happy now :)
Also for the record my problem with libxml2 happened with eww.
