### ISSUE TITLE
M-return and M-S-return stop working sometimes

### ISSUE THREAD

**Issue by wilcoxjay** [cpitclaudel/company-coq#79] opened 2016-02-11 04:52 UTC
I get the error `or: [yas] 'yas-expand-snippet' needs properly setup 'yas-minor-mode'`

**Comment by cpitclaudel** [comment] 2016-02-11 12:06
I wonder if this is similar to the company-mode thing. Does it happen in the same circumstances?

**Comment by wilcoxjay** [comment] 2016-02-11 17:19
No, I can't reproduce it simply by opening another file.

**Comment by wilcoxjay** [comment] 2016-02-11 17:52
Another symptom of the same(?) bug is that whenever I press return to accept a completion, it moves my point to the *beginning* of the completed word, instead of to the end, and prints the error `Company: Back-end company-coq-master-backend error "[yas] 'yas-expand-snippet' needs properly setup 'yas-minor-mode'" with args (post-completion constructor)`

**Comment by cpitclaudel** [comment] 2016-02-11 18:03
I'm going to guess that `M-x yas-minor-mode` would fix it. But I'm not sure why it's happening to begin with :/

**Comment by wilcoxjay** [comment] 2016-02-11 23:06
`M-x yas-minor-mode` twice (once to disable it, once to enable it) does indeed fix it.

**Comment by cpitclaudel** [comment] 2016-02-11 23:17
Thanks for testing. Do you have a recipe to reproduce the issue?

**Comment by wilcoxjay** [comment] 2016-02-11 23:42
Unfortunately no, I had just left the broken buffer open until now :)

I'll keep an eye out for when it happens again in the future.

**Comment by jinyangustc** [comment] 2016-03-03 08:50
I have the same issue like @wilcoxjay , that is my curse jumps to the beginning of the completed word and get the error. I am using spacemacs. Just add this layer (https://github.com/jinyangustc/spacemacs-coq) to the `private/` folder and open a `.v` file, type and complete the `intros`, then the problem should be produced. My whole config of spacemacs can be found here (https://github.com/jinyangustc/dotfiles/blob/master/spacemacs).

**Comment by cpitclaudel** [comment] 2016-03-03 18:14
@jinyangustc Does running `M-x yas-minor-mode` fix it? Does it happen every time?

**Comment by cpitclaudel** [comment] 2016-03-03 18:17
Ah, I see it :)

**Comment by cpitclaudel** [comment] 2016-03-03 18:17
The trick is to open two Coq buffers without company-coq-mode, then turn it on in the first one and try to complete in the second one.

**Comment by jinyangustc** [comment] 2016-03-04 02:57
"Does running `M-x ays-minor-mode` fix it?", no, it doesn't work for me. Restart `company-coq-mode` can fix it.

I tried the new version `20160303.1020`. Completing `intros` indeed no longer triggers the problem. However, I still encounter the problem. If I complete words by hitting `return`, then the problem happens less frequently (but still happens). If I complete words by hitting `tab`, then the problem occur  immediately.

**Comment by cpitclaudel** [comment] 2016-03-04 06:13
@jinyangustc Can you give more detailed directions? Does it depend on Spacemacs?
If I can reproduce the problem, it will be easy to fix it. But otherwise I can't do much. So a full recipe would be very convenient.

**Comment by jinyangustc** [comment] 2016-03-05 08:25
@cpitclaudel I just tried to build a minimum Spacemacs configuration and I do get the same problem. Here is a [gist](https://gist.github.com/jinyangustc/ff93130de6c7a03dcb05) to show how to set up the config and reproduce the problem. I am not sure if it is related to Spacemacs. I am a pure emacs "user" (have very few experience on elisp) and just migrate to Spacemacs about months ago. Since the Spacemacs is very popular, I think many people could benefit from a `coq-layer` (if there exist). Such as my classmates  who need to use coq/proof-general and never use emacs before. If this problem is about Spacemacs, I'll try to ask for some help in Spacemacs community.

**Comment by jinyangustc** [comment] 2016-03-05 08:34
1. I disable the `company-coq-mode` and enable it. 
2. Type `Indu` then hit return and use `Ctrl+j` to select `induction term as disj_conj_intro_pattern`.
3. `tab` to `term` and type `n`.
4. Then type `ESC` to normal mode (Spacemacs uses `evil`).
5. Then try to complete any word, say, `Definition indent := term.`

Here is the Message buffer in the process:
``` text
Showing all blocks ... done
Company-Coq mode enabled in current buffer
Welcome to company-coq! Use M-x company-coq-tutorial to get started.
[yas] snippet expanded.
[yas] Snippet 3 exited.
Error in post-command-hook (yas--post-command-handler): (wrong-type-argument number-or-marker-p (8783 . #<marker in no buffer>))
Auto-saving...
company-call-backend-raw: Company: backend company-coq-master-backend error "[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'" with args (post-completion Definition ident := term.)
Auto-saving...
```

**Comment by cpitclaudel** [comment] 2016-03-06 05:24
Thanks for the detailed reproduction. I installed spacemacs, added the extra layer, loaded Proof General, started completion and so on, but I still can't reproduce this issue :/

Was I not careful enough with the repro steps? I'll admit that spacemacs was a bit confusing to me; it took me a number of attempts just to install company-coq, as it seemed to uninstall it every time I restarted.

**Comment by jinyangustc** [comment] 2016-03-06 08:09
I am so sorry that I forget to mention you need to rename `spacemacs-coq` to `coq` and then put it in the `private` folder. `company-coq` should be installed automatically. I've edited the gist (line 4 in `recipe.txt`.). Now you should get all the packages installed automatically. I also change the edit style to `emacs` so that you may feel more natural (however, according to my understanding of spacemacs, even in `emacs` edit style, there is still `evil` behind it).

Is it possible related to Emacs version? My system environment:
``` text
Mac OS X 10.10.5
Emacs 25.0.50.1
```

**Comment by cpitclaudel** [comment] 2016-07-15 10:39
I tried reproducing this, but I couldn't :/ Since this thread's original issue is fixed, I'll close this ticket. @jinyangustc, feel free to open a separate issue if this still happens, with detailed repro steps starting from emacs -Q :)

**Closed by cpitclaudel** 2016-07-15 10:39 UTC
