### ISSUE TITLE
company-coq is a few orders of magnitude slower than vanilla PG when the file contains unicode characters

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/company-coq#145] opened 2016-12-21 00:00 UTC
Consider this file:
```coq
Require Import Coq.Classes.Morphisms.
Require Import Coq.Sets.Ensembles.
Require Import Coq.Classes.Morphisms.
Require Import Coq.Sets.Ensembles.
Require Import Coq.Classes.Morphisms.
Require Import Coq.Sets.Ensembles.
Require Import Coq.Classes.Morphisms.
Require Import Coq.Sets.Ensembles.
Set Implicit Arguments.

Local Coercion is_true : bool >-> Sortclass.

Reserved Notation "# x" (at level 70).
Reserved Infix "@" (left associativity, at level 77).
Reserved Notation "\ x , e" (at level 78).
Reserved Notation "\ ! , e" (at level 78).
Reserved Infix "⊓" (at level 80).
Reserved Infix "⊔" (at level 80).
Reserved Infix "##" (at level 60, right associativity).
Reserved Infix "=s" (at level 70, no associativity).
Reserved Infix "=b" (at level 70, no associativity).
Reserved Notation "s ~= [ ch ]" (at level 70, no associativity).
Reserved Infix "=?" (at level 70).
Reserved Infix "<=?" (at level 70).
Reserved Infix "<?" (at level 70).
Reserved Infix "?=" (at level 70).
Reserved Notation "'⊤'".
Reserved Notation "'⊥'".


(** Quoting the FRAP book (http://adam.chlipala.net/frap/frap_book.pdf): *)
(** ** 7.1. Definition of an Abstract Interpretation *)
(** An abstract interpretation is a particular sort of abstraction, of
    the kind we met in studying model checking. In that more general
    setting, we can represent concrete states with any sorts of
    abstract states. In abstract interpretation, we most commonly
    associate each variable with an independent abstract description.
    One example, which we’ll formalize in more detail shortly, would
    be to label each variable as “even,” “odd,” or “either.” *)
(** Definition 7.1. An abstract interpretation (for our example
    imperative language) is a tuple [⟨D, ⊤, C, +̂, -̂, ×̂, ⊔, ~⟩], where
    [D] is a set (the domain of the analysis); [⊤ ∈ D]; [C : ℕ → D];
    [+̂], [-̂], [×̂], [⊔] [: D × D → D]; and [~ ⊆ ℕ × D]. The idea is
    that: *)
(** - Abstract versions of numbers are [D] values. *)
(** - [⊤] (“top”) is the least specific abstract value, representing
      any concrete value. *)
(** - [C] maps any constant to its most precise abstraction. *)
(** - [+̂], [-̂], and [×̂] push abstraction through arithmetic operators,
      calculating their most precise abstractions. *)
(** - [⊔] (“join”) computes the least upper bound of two abstract
      values: the most specific value that represents any value
      associated with either input. *)
(** - [~] formalizes the idea of which concrete values are covered by
      which abstract values. *)
Delimit Scope ai_scope with ai.
Local Open Scope ai_scope.
Section definition.
  (** We generalize to a set [V] of values. *)

  (** "For [a], [b] [∈ D], define [a ⊑ b] to mean [∀ n ∈ ℕ. (n ~ a) ⇒
      (n ~ b)]. That is, [b] is at least as general as [a]. *)

  (** [V] is concrete values, [D] is abstract values *)
  Class AbstractInterpretationOn (V D : Type) :=
    { bottom : D where "'⊥'" := bottom : ai_scope;
      constant : V -> D;
      empty : D;
      join : D -> D -> D where "x ⊔ y" := (join x y) : ai_scope;
      concat : D -> D -> D where "x ++ y" := (concat x y) : ai_scope;
      is_concatV : V -> V -> V -> Prop;
      related : Ensemble V -> D -> Prop;
      state_leb : D -> D -> bool where "x <=? y" := (state_leb x y) : ai_scope;
      state_ltb : D -> D -> bool
      := fun x y => ((x <=? y) && negb (y <=? x))%bool;
      related_correct : forall a b, (forall v, related v a -> related v b) <-> a <=? b;
      bottom_bottom : forall a, (⊥ <=? a);
      constant_correct : forall n, related (Singleton _ n) (constant n);
      concat_correct  : forall a b a' b',
          related a a' -> related b b'
          -> related (fun ab => exists a0 b0, Ensembles.In _ a a0 /\ Ensembles.In _ b b0 /\ is_concatV a0 b0 ab) (a' ++ b');
      concat_Proper : Proper (state_leb ==> state_leb ==> state_leb) concat;
      join_correct_l : forall a b, a <=? (a ⊔ b);
      join_correct_r : forall a b, b <=? (a ⊔ b);
      state_gtb_wf : well_founded (Basics.flip state_ltb) }.
End definition.
```

Consider the difference between these behaviors:
Vanilla PG:
![ezgif com-7bc1cf635b](https://cloud.githubusercontent.com/assets/396076/21372610/577a944a-c6e6-11e6-9c77-48dfbe5376ae.gif)
Company-Coq:
![ezgif com-f792f98a1e](https://cloud.githubusercontent.com/assets/396076/21372616/5ce72858-c6e6-11e6-9980-806244464f96.gif)
Company-Coq, disabled in the middle of processing:
![ezgif com-68accaac9e](https://cloud.githubusercontent.com/assets/396076/21372622/67bfa872-c6e6-11e6-8916-aa77e9110c8a.gif)

**Comment by cpitclaudel** [comment] 2016-12-21 01:24
Fascinating.  I wonder why everything is so slow on your machine — processing this whole file is instantaneous for me, both with and without PG.

Which Emacs are you using? Do you have the unicode fonts patch applied, or not?

**Comment by JasonGross** [comment] 2016-12-21 04:26
The version of 24 that's on trusty, I think.  And no, I haven't applied the patch.

**Comment by cpitclaudel** [comment] 2016-12-21 15:26
Ok.  And is prettification enabled in company-coq?

**Comment by cpitclaudel** [comment] 2016-12-21 22:15
Thanks.  Can you try with a patched Emacs, and see if the difference persists?

**Comment by JasonGross** [comment] 2016-12-22 20:21
Interestingly, the issue seems to be far more severe when emacs is full-screen (tests suggest that it's the size of the window, and not the full-screenness nor whether the frames are displayed vertically vs horizontal split, that matters).  In the following, unpatched is on the left, patched is on the right:
With company-coq, not full screen:
![ezgif com-3c5d948fb8](https://cloud.githubusercontent.com/assets/396076/21438708/768cdf1e-c858-11e6-8b43-cbcb2ada51f7.gif)
With company-coq, full-screen on separate monitors:
![ezgif com-50b4ca1478](https://cloud.githubusercontent.com/assets/396076/21438946/7748c372-c859-11e6-9f17-8df445146b2d.gif)
Without company-coq, full-screen on separate monitors:
![ezgif com-b46ef5fce8](https://cloud.githubusercontent.com/assets/396076/21438948/7bb089fe-c859-11e6-8a56-9f3dffac3891.gif)
Side-by-side, only patched version, company-coq on left, non-company-coq on right:
![ezgif com-6a05992c19](https://cloud.githubusercontent.com/assets/396076/21439048/dc0a5794-c859-11e6-9fa4-97cf1ae5fb18.gif)

**Comment by cpitclaudel** [comment] 2016-12-22 21:47
This doesn't sound too surprising: the more characters are shown, the slower Windows will get.  Please try with a patched Emacs?

**Comment by JasonGross** [comment] 2016-12-22 21:55
> the slower Windows will get

I assume you mean emacs?  This is on Linux.

> Please try with a patched Emacs?

In the first three gifs in the previous post, the emacs on the right hand half is patched.

**Comment by cpitclaudel** [comment] 2016-12-22 22:09
No, windows as in bits of the part of the screen that is visible (windows in the Emacs sense, I shouldn't have put the capital there :/)

I think I didn't look at the gifs carefully enough.  But the third one (patched with and without company-coq) seems to be more or less the same speed, right?  That is; I do expect Emacs to be a bit slower with company-coq.

**Comment by JasonGross** [comment] 2016-12-22 22:15
Yes, with the patch, it seems fine with and without company-coq.

**Comment by Blaisorblade** [comment] 2019-10-30 20:39
I also suffered from this problem a while ago (and stopped using company-coq). What is this Emacs patch? I recall I failed to find it...

**Comment by cpitclaudel** [comment] 2019-10-30 21:00
It was merged into Emacs a while ago.  Which Emacs are you using?

**Comment by Blaisorblade** [comment] 2019-10-30 21:59
Emacs 26.3 with Spacemacs develop.

Let's assume I ran into some other bug then, and close the issue? 

I might try again if I find time; Spacemacs also suffered other performance bugs (e.g. https://github.com/ProofGeneral/PG/issues/427).

**Comment by cpitclaudel** [comment] 2019-10-30 23:35
Sounds good. Let's open a new one if the bug persists.

**Closed by cpitclaudel** 2019-10-30 23:35 UTC

**Comment by paldepind** [comment] 2020-02-24 14:59
I experience the same bug or a similar one. I'm using Emacs 26.3 with the doom-emacs configuration. Evaluating Coq in a is much slower when company-coq is enabled. Similar to what @JasonGross describes the performance becomes worse the larger the Emacs window is.

Should I open a new issue?

**Comment by cpitclaudel** [comment] 2020-02-29 18:03
You can open a new issue; I think it would be good to confirm first that the issue is specific to company-coq
